# Generated by Django 5.1 on 2026-03-23 03:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('project_type', models.CharField(choices=[('new', 'New Interior'), ('renovation', 'Renovation')], default='new', max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('house', 'Independent House'), ('penthouse', 'Penthouse')], default='apartment', max_length=20)),
                ('style', models.CharField(blank=True, default='', max_length=50)),
                ('tier', models.CharField(blank=True, default='', max_length=10)),
                ('rooms_breakdown', models.JSONField(default=list)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_percent_snapshot', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent_snapshot', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('reviewed', 'Reviewed'), ('converted', 'Converted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estimation_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
